### ISSUE TITLE
Scripts to generate adversarial data

### ISSUE THREAD

**Issue by HuihuiChyan** [princeton-nlp/LLMBar#1]
Hi thank you for your nice job. I wonder if you could provide the scripts to construct the adversarial data? For example, GPT-Inst or Neighbor. It will be of great help to me.
Best regards.

**Comment by Zhiyuan-Zeng** [comment]
Thanks for your interest. We have not cleaned up the code yet, and I have sent you the uncleaned code.

**Comment by HuihuiChyan** [comment]
Thank you!

**Comment by HuihuiChyan** [comment]
Fixed. Thank you.

**Comment by fabrahman** [comment]
Hi @Zhiyuan-Zeng , would you be able to share the uncleaned code ?
faezeb [at] allenai.org

Thanks much

**Comment by Zhiyuan-Zeng** [comment]
Hi @fabrahman, thanks for your interest! Let me reach out to you to share the uncleaned code.

**Comment by fabrahman** [comment]
> Hi @fabrahman, thanks for your interest! Let me reach out to you to share the uncleaned code.

Thank you! I  actually implemented it but wanted to cross check some hyperparamers/details like similarity thresholds, did you only sample from single turn conversations, and if for each dataset (alpaca, sharegpt, and openassist) you retrieve from their respective data?
