### ISSUE TITLE
LLMBar metrics on newer models

### ISSUE THREAD

**Issue by DavidFarago** [princeton-nlp/LLMBar#3]
LLMBar metrics on newer models, esp. GPT-4o, GPT-4o-mini, Claude 3.5 sonnet, Llama-3.1-8B-Instruct, Llama-3.1-70B-Instruct, Llama-Guard-3-8B, Llama-Guard-3-8B-INT8, gemma-2-2b-it, gemma-2-9b-it, would be awesome.

Are these results available somewhere? Or is there LLMBar running online somewhere, like LMEval? 

Why does the `README.md` say `{base_llm} is one of GPT-4, ChatGPT, LLaMA2, PaLM2, Falcon, and ChatGPT-0301.`?

**Comment by Zhiyuan-Zeng** [comment]
Hi @DavidFarago, thank you for your interest and for your questions! Unfortunately, we have not yet added results for the newer models you mentioned -- apologies for that.

We noticed that LLMBar has been incorporated into [RewardBench](https://huggingface.co/spaces/allenai/reward-bench). You can view the results of LLM evaluators (including many newer models you mentioned) by looking at the models with "Generative" as their "Model Type". Please note that they may have used different prompts than ours, so their results should not be directly compared to ours; but you can always compare different models within their results.

**Comment by DavidFarago** [comment]
Cool, under RewardBenchDetailed, even the metrics for LLMBar subsets are listed and can be sorted.
